package accountingsystem;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author HPLaptop
 */
import java.sql.PreparedStatement;
import java.sql.Connection;
public class customerformpage extends javax.swing.JFrame {

    /**
     * Creates new form customerformpage
     
     * 
     * 
     * 
     * 
     **/
    public customerformpage() {
        initComponents();
        setSize(500,500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cname = new javax.swing.JTextField();
        compname = new javax.swing.JTextField();
        cityplace = new javax.swing.JTextField();
        phno = new javax.swing.JTextField();
        sub1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        cname.setText("customer name");
        getContentPane().add(cname);
        cname.setBounds(120, 40, 140, 22);

        compname.setText("company name");
        getContentPane().add(compname);
        compname.setBounds(120, 80, 140, 22);

        cityplace.setText("city");
        getContentPane().add(cityplace);
        cityplace.setBounds(120, 130, 64, 22);

        phno.setText("phone no.");
        getContentPane().add(phno);
        phno.setBounds(120, 180, 69, 20);

        sub1.setText("submit");
        sub1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub1ActionPerformed(evt);
            }
        });
        sub1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                sub1PropertyChange(evt);
            }
        });
        getContentPane().add(sub1);
        sub1.setBounds(170, 230, 72, 23);

        jButton2.setText("home");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(300, 20, 72, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        NewJFrame.main(new String[2]);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void sub1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub1ActionPerformed
        // TODO add your handling code here:
        try{
             Connection con=InitConnection.initConn();
             PreparedStatement ps=con.prepareStatement("insert into customer(cname,comn,city,mob) values(?,?,?,?)");
             ps.setString(1,cname.getText());
             ps.setString(2,compname.getText());
             ps.setString(3,cityplace.getText());
             ps.setInt(4,Integer.parseInt(phno.getText()));
             
             int x=ps.executeUpdate();
             System.out.println(x+"data inserted");
             
             cname.setText("");
             compname.setText("");
             cityplace.setText("");
             phno.setText("");
             
        }catch(Exception tt)
        {
            System.out.println(tt);
        }
    }//GEN-LAST:event_sub1ActionPerformed

    private void sub1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_sub1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_sub1PropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customerformpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customerformpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customerformpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customerformpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customerformpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cityplace;
    private javax.swing.JTextField cname;
    private javax.swing.JTextField compname;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField phno;
    private javax.swing.JButton sub1;
    // End of variables declaration//GEN-END:variables
}
