/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package accountingsystem;

/**
 *
 * @author HPLaptop
 */
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.util.Vector;
import java.sql.PreparedStatement;
import java.util.Date;


public class purchaseformpage extends javax.swing.JFrame {

    /**
     * Creates new form purchaseformpage
     */
    int invno,cid1,pid1;
    Connection con=null;
    Vector v1=null;
    Vector v2=null;
    Vector v3=null;
    Vector v4=null;
    
    public void getData()
    {
        try{
            con=InitConnection.initConn();
            Statement stm=con.createStatement();
            //for invoice no
            ResultSet rs1=stm.executeQuery("select invno from purchase");
            if(rs1.next())
            {
                invno=rs1.getInt(1);
                while(rs1.next())
                {
                    invno=rs1.getInt(1);
                }
               invno=invno+1; 
            }else{
                invno=101;
            }
            inv.setText(invno+"");
            
            //query to get customer data
            ResultSet rs2=stm.executeQuery("select id,cname,city from customer" );
            v1=new Vector();
             v2=new Vector();
             
             while(rs2.next())
             {
                 v1.addElement(rs2.getInt(1));
                  cb1.addItem(rs2.getString(2));
                  v2.addElement(rs2.getString(3));
             }
             
             //query for product data
             
             ResultSet rs3=stm.executeQuery("select pid,pname,pprice from product" );
            v3=new Vector();
             v4=new Vector();
             
             while(rs3.next())
             {
                 v3.addElement(rs3.getInt(1));
                  cb2.addItem(rs3.getString(2));
                  v4.addElement(rs3.getInt(3));
             }
             
             
            
        }catch(Exception tt)
        {
            System.out.println(tt);
            
        }
    }
    public purchaseformpage() {
        initComponents();
        setSize(500,500);
            getData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inv = new javax.swing.JTextField();
        cb2 = new javax.swing.JComboBox<>();
        cb1 = new javax.swing.JComboBox<>();
        city = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pp = new javax.swing.JTextField();
        qty = new javax.swing.JTextField();
        ta = new javax.swing.JTextField();
        sub3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        inv.setText("invoice no");
        getContentPane().add(inv);
        inv.setBounds(30, 30, 70, 22);

        cb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb2ActionPerformed(evt);
            }
        });
        getContentPane().add(cb2);
        cb2.setBounds(240, 90, 72, 22);

        cb1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb1ItemStateChanged(evt);
            }
        });
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });
        cb1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cb1PropertyChange(evt);
            }
        });
        getContentPane().add(cb1);
        cb1.setBounds(240, 30, 72, 22);

        city.setText("city");
        getContentPane().add(city);
        city.setBounds(30, 90, 64, 22);

        jLabel1.setText("select name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 30, 80, 16);

        jLabel2.setText("select product");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(150, 90, 80, 16);

        pp.setText("purchase price");
        getContentPane().add(pp);
        pp.setBounds(31, 150, 90, 22);

        qty.setText("quantity");
        qty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtyActionPerformed(evt);
            }
        });
        getContentPane().add(qty);
        qty.setBounds(160, 150, 64, 22);

        ta.setText("ttl amount");
        getContentPane().add(ta);
        ta.setBounds(270, 150, 71, 22);

        sub3.setText("submit");
        sub3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub3ActionPerformed(evt);
            }
        });
        getContentPane().add(sub3);
        sub3.setBounds(180, 220, 72, 23);

        jButton2.setText("home");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(50, 220, 72, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        NewJFrame.main(new String[2]);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cb1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cb1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_cb1PropertyChange

    private void cb1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb1ItemStateChanged
        // TODO add your handling code here:
        try{
            int x=cb1.getSelectedIndex();
            city.setText((String)v2.get(x));
            cid1=(Integer)v1.get(x);
            
        }catch(Exception tt)
        {
            System.out.println(tt);
        }
    }//GEN-LAST:event_cb1ItemStateChanged

    private void cb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb2ActionPerformed
        // TODO add your handling code here:
         try{
            int x=cb2.getSelectedIndex();
            pp.setText((Integer)v4.get(x)+"");
            pid1=(Integer)v3.get(x);
            
        }catch(Exception tt)
        {
            System.out.println(tt);
        }
    }//GEN-LAST:event_cb2ActionPerformed

    private void qtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtyActionPerformed
        // TODO add your handling code here:
        int t=Integer.parseInt(pp.getText());
         int j=Integer.parseInt(qty.getText());
         ta.setText(t*j+"");
        
    }//GEN-LAST:event_qtyActionPerformed

    private void sub3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub3ActionPerformed
        // TODO add your handling code here:
        try{
            PreparedStatement ps=con.prepareStatement("insert into purchase(invno,cid,prodid,purprice,qty,tamount,pdate) values(?,?,?,?,?,?,?)");
           ps.setInt(1,Integer.parseInt(inv.getText()));
            ps.setInt(2,cid1);
             ps.setInt(3,pid1);
              ps.setInt(4,Integer.parseInt(pp.getText()));
               ps.setInt(5,Integer.parseInt(qty.getText()));
                ps.setInt(6,Integer.parseInt(ta.getText()));
                 ps.setString(7,new Date().toString());
                 
                 ps.executeUpdate();
                 
                 
                 
//                 DefaultTableModel model=(DefaultTableModel)jTable1.getMode1();
//                 model.addRow(new Object[]{inv.getText(),cid1,pid1,pp.getText(),qty.getText(),ta.getText(),new Date().toString()});
//                 
//         
      }catch(Exception tt)
        {
             System.out.println(tt);
        }
    }//GEN-LAST:event_sub3ActionPerformed

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(purchaseformpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(purchaseformpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(purchaseformpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(purchaseformpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new purchaseformpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb1;
    private javax.swing.JComboBox<String> cb2;
    private javax.swing.JTextField city;
    private javax.swing.JTextField inv;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField pp;
    private javax.swing.JTextField qty;
    private javax.swing.JButton sub3;
    private javax.swing.JTextField ta;
    // End of variables declaration//GEN-END:variables
}
