/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package accountingsystem;

import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.util.Vector;
import java.sql.PreparedStatement;
import java.util.Date;

/**
 *
 * @author HPLaptop
 */
public class Salesformpage extends javax.swing.JFrame {

    /**
     * Creates new form Salesformpage
     */
     int invno,cid1,pid1;
    Connection con=null;
    Vector v1=null;
    Vector v2=null;
    Vector v3=null;
    Vector v4=null;
     
    public void getData()
    {
        try{
            con=InitConnection.initConn();
            Statement stm=con.createStatement();
            //for invoice no
            ResultSet rs1=stm.executeQuery("select invno from purchase");
            if(rs1.next())
            {
                invno=rs1.getInt(1);
                while(rs1.next())
                {
                    invno=rs1.getInt(1);
                }
               invno=invno+1; 
            }else{
                invno=101;
            }
             inv1.setText(invno+"");
            
            //query to get customer data
            ResultSet rs2=stm.executeQuery("select id,cname,city from customer" );
            v1=new Vector();
             v2=new Vector();
             
             while(rs2.next())
             {
                 v1.addElement(rs2.getInt(1));
                  cb11.addItem(rs2.getString(2));
                  v2.addElement(rs2.getString(3));
             }
             
             //query for product data
             
             ResultSet rs3=stm.executeQuery("select pid,pname,sprice from product" );
            v3=new Vector();
             v4=new Vector();
             
             while(rs3.next())
             {
                 v3.addElement(rs3.getInt(1));
                  cb12.addItem(rs3.getString(2));
                  v4.addElement(rs3.getInt(3));
             }
             
            
             
             
                }catch(Exception tt)
        {
            System.out.println(tt);
            
        }
    }
    public Salesformpage() {
        initComponents();
         setSize(500,500);
            getData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inv1 = new javax.swing.JTextField();
        city1 = new javax.swing.JTextField();
        sp = new javax.swing.JTextField();
        cb11 = new javax.swing.JComboBox<>();
        cb12 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        sub4 = new javax.swing.JButton();
        qty1 = new javax.swing.JTextField();
        ta1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        inv1.setText("invoice no");
        inv1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inv1ActionPerformed(evt);
            }
        });
        getContentPane().add(inv1);
        inv1.setBounds(40, 30, 70, 22);

        city1.setText("city");
        getContentPane().add(city1);
        city1.setBounds(40, 90, 64, 22);

        sp.setText("selling price");
        getContentPane().add(sp);
        sp.setBounds(40, 150, 90, 22);

        cb11.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb11ItemStateChanged(evt);
            }
        });
        getContentPane().add(cb11);
        cb11.setBounds(280, 30, 72, 22);

        cb12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb12ActionPerformed(evt);
            }
        });
        getContentPane().add(cb12);
        cb12.setBounds(280, 90, 72, 22);

        jLabel1.setText("select name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(167, 30, 80, 16);

        jLabel2.setText("select product");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(167, 90, 80, 16);

        jButton1.setText("home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(110, 210, 72, 23);

        sub4.setText("submit");
        sub4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub4ActionPerformed(evt);
            }
        });
        getContentPane().add(sub4);
        sub4.setBounds(230, 210, 72, 23);

        qty1.setText("qty");
        qty1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qty1ActionPerformed(evt);
            }
        });
        getContentPane().add(qty1);
        qty1.setBounds(170, 150, 64, 22);

        ta1.setText("total amount");
        getContentPane().add(ta1);
        ta1.setBounds(270, 150, 90, 22);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inv1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inv1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inv1ActionPerformed

    private void qty1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qty1ActionPerformed
        // TODO add your handling code here:
        int t=Integer.parseInt(sp.getText());
         int j=Integer.parseInt(qty1.getText());
         ta1.setText(t*j+"");
        
    }//GEN-LAST:event_qty1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        NewJFrame.main(new String[2]);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cb11ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb11ItemStateChanged
        // TODO add your handling code here:
        try{
            int x=cb11.getSelectedIndex();
            city1.setText((String)v2.get(x));
            cid1=(Integer)v1.get(x);
            
        }catch(Exception tt)
        {
            System.out.println(tt);
        }
                
    }//GEN-LAST:event_cb11ItemStateChanged

    private void cb12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb12ActionPerformed
        // TODO add your handling code here:
      try{
            int x=cb12.getSelectedIndex();
            sp.setText((Integer)v4.get(x)+"");
           
            pid1=(Integer)v3.get(x);
            
        }catch(Exception tt)
        {
            System.out.println(tt);
        }
              
    }//GEN-LAST:event_cb12ActionPerformed

    private void sub4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub4ActionPerformed
        // TODO add your handling code here:
       try{
            PreparedStatement ps=con.prepareStatement("insert into sales(invno,cid,prodid,saleprice,qty,tamount,pdate) values(?,?,?,?,?,?,?)");
           ps.setInt(1,Integer.parseInt(inv1.getText()));
            ps.setInt(2,cid1);
             ps.setInt(3,pid1);
              ps.setInt(4,Integer.parseInt(sp.getText()));
               ps.setInt(5,Integer.parseInt(qty1.getText()));
                ps.setInt(6,Integer.parseInt(ta1.getText()));
                 ps.setString(7,new Date().toString());
                 
                 ps.executeUpdate();
                 
         
      }catch(Exception tt)
        {
             System.out.println(tt);
         }
                     
    }//GEN-LAST:event_sub4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Salesformpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Salesformpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Salesformpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Salesformpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Salesformpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb11;
    private javax.swing.JComboBox<String> cb12;
    private javax.swing.JTextField city1;
    private javax.swing.JTextField inv1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField qty1;
    private javax.swing.JTextField sp;
    private javax.swing.JButton sub4;
    private javax.swing.JTextField ta1;
    // End of variables declaration//GEN-END:variables
}
