/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package accountingsystem;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.table.*;

/**
 *
 * @author HPLaptop
 */
public class StockTable extends javax.swing.JFrame {

    /**
     * Creates new form StockTable
     */
    public StockTable() {
        initComponents();
           setSize(900,500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "invno", "cid", "prodid", "purprice", "qty", "tamount", "pdate"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(6, 46, 640, 250);

        jButton1.setText("show stock Table");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 10, 130, 23);

        jButton2.setText("home");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(170, 10, 72, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
         try{
              Connection con=InitConnection.initConn();
         Statement st=con.createStatement();
         
         String sql="select * from purchase";
         ResultSet rs=st.executeQuery(sql);
         
         while(rs.next())
             
             
         {
             String invno=String.valueOf(rs.getInt("invno"));
             String cid=String.valueOf(rs.getInt("cid"));
             String prodid=String.valueOf(rs.getInt("prodid"));
             String purprice=String.valueOf(rs.getInt("purprice"));
             String qty=String.valueOf(rs.getInt("qty"));
             String tamount=String.valueOf(rs.getInt("tamount"));
             String pdate=rs.getString("pdate");
             
             String tbData[]={invno,cid,prodid,purprice,qty,tamount,pdate};
             DefaultTableModel tblModel=(DefaultTableModel)jTable1.getModel();
             //                 DefaultTableModel model=(DefaultTableModel)jTable1.getMode1();

             
             tblModel.addRow(tbData);
         }
         
        
         
         String sql1="select * from sales";
         ResultSet rs1=st.executeQuery(sql1);
         
         while(rs1.next())
             
             
         {
             String invno=String.valueOf(rs1.getInt("invno"));
             String cid=String.valueOf(rs1.getInt("cid"));
             String prodid=String.valueOf(rs1.getInt("prodid"));
             String purprice=String.valueOf(rs1.getInt("saleprice"));
             String qty=String.valueOf(rs1.getInt("qty"));
             String tamount=String.valueOf(rs1.getInt("tamount"));
             String pdate=rs1.getString("pdate");
             
             String tbData1[]={invno,cid,prodid,purprice,qty,tamount,pdate};
             DefaultTableModel tblModel=(DefaultTableModel)jTable1.getModel();
             //                 DefaultTableModel model=(DefaultTableModel)jTable1.getMode1();

             
             tblModel.addRow(tbData1);
         }
         
             
         }catch(Exception tt)
         {
             System.out.println(tt);
         }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
        NewJFrame.main(new String[2]);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StockTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StockTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StockTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StockTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StockTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
